Upgrade to Smack v4.2.0, Removing <relocations>
Upgrade to Smack version 4.2.0 

Removing <relocations> is due to the fact that <relocations> in the pom.xml file causes an error 
«org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class org.graylog.plugins.jabber.shaded.smack.tcp.XMPPTCPConnectionConfiguration» 
https://github.com/graylog-labs/graylog-plugin-jabber/issues/11